const db=supabase.createClient(AVIONICA_SUPABASE_URL,AVIONICA_SUPABASE_KEY);let employees=[],current=null,admin=false;const S=document.getElementById("screen");const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const ini=n=>String(n||"").split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();const nav=[["inicio","⌂ Inicio"],["cuadrantes","▦ Cuadrantes"],["inventario","▤ Inventario"],["noticias","◈ Noticias"],["novedades","✦ Novedades"],["perfil","◯ Mi perfil"]];
async function load(){let r=await db.from("profiles").select("id,full_name,phone,role").order("full_name");if(r.error){S.innerHTML=`<div class=login><div class=pick><div class=head><div class=logo>A</div><h1>AVIÓNICA</h1><p class=muted>${esc(r.error.message)}</p></div></div></div>`;return false}employees=r.data||[];return true}
async function choose(){if(!await load())return;S.innerHTML=`<div class=login><div class=pick><div class=head><div class=logo>A</div><h1>AVIÓNICA</h1><p class=muted>Selecciona tu nombre para entrar</p></div><div class=people>${employees.map(e=>`<button class=person onclick="enter('${e.id}')"><div class=avatar>${ini(e.full_name)}</div><b>${esc(e.full_name)}</b><div class=muted>Miembro del equipo</div></button>`).join("")}</div><div class=admin><button class=btn onclick=pin()>⚙ Administración</button></div></div></div>`}
async function enter(id){current=employees.find(e=>e.id===id);admin=false;render("inicio")}
async function render(page){let title=page==="inicio"?"Inicio":page[0].toUpperCase()+page.slice(1);S.innerHTML=`<aside class=side id=side><div class=brand><div class=logo>A</div><div><b>AVIÓNICA</b><small>Portal del equipo</small></div></div><div class=nav>${nav.map(n=>`<button type="button" class=${page===n[0]?"active":""} data-page="${n[0]}">${n[1]}</button>`).join("")}${admin?`<button type="button" class=${page==="admin"?"active":""} data-page="admin">⚙ Administración</button>`:""}</div><div class=sidefoot>Supabase · v4</div></aside><main class=main><header class=top><div><button type="button" class=menu id=menuBtn>☰</button><h2>${title}</h2></div><div class=profile><div class=avatar>${admin?"AD":ini(current.full_name)}</div><div><b>${admin?"Administrador":esc(current.full_name)}</b><div class=muted>${admin?"Control general":"Empleado"}</div></div><button type="button" class=logout id=logoutBtn>Salir</button></div></header><div class=content id=content></div></main>`;document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>render(b.dataset.page)));document.getElementById("menuBtn")?.addEventListener("click",()=>document.getElementById("side")?.classList.toggle("open"));document.getElementById("logoutBtn")?.addEventListener("click",choose);await ({inicio,cuadrantes,inventario,noticias,novedades,perfil,admin:adminPage})[page]()}
async function inicio(){let [a,b,c,d]=await Promise.all([admin?db.from("shifts").select("*",{count:"exact",head:true}):db.from("shifts").select("*",{count:"exact",head:true}).eq("employee_id",current.id),db.from("inventory").select("*",{count:"exact",head:true}),db.from("news").select("*",{count:"exact",head:true}),db.from("updates").select("*",{count:"exact",head:true})]);content.innerHTML=`<div class=hero><h2>Hola, ${esc((admin?"Administrador":current.full_name).split(" ")[0])} 👋</h2><div>Datos reales cargados desde Supabase.</div></div><div class=grid>${[["Turnos",a.count],["Inventario",b.count],["Noticias",c.count],["Novedades",d.count]].map(x=>`<div class="card stat"><span class=muted>${x[0]}</span><b>${x[1]??0}</b></div>`).join("")}</div>`}
async function cuadrantes(){let q=admin?db.from("shifts").select("*,profiles(full_name)").order("date"):db.from("shifts").select("*").eq("employee_id",current.id).order("date");let r=await q;content.innerHTML=`<div class=row><h3>Cuadrantes</h3>${admin?'<button class=btn onclick=newShift()>+ Añadir turno</button>':""}</div><div class=card><table class=table><tr><th>Fecha</th><th>Empleado</th><th>Horario</th><th>Servicio</th><th></th></tr>${(r.data||[]).map(x=>`<tr><td>${x.date}</td><td>${esc(x.profiles?.full_name||current.full_name)}</td><td>${x.start_time||""} – ${x.end_time||""}</td><td>${esc(x.service)}</td><td>${admin?`<button class="smallbtn danger" onclick="del('shifts','${x.id}','cuadrantes')">Eliminar</button>`:""}</td></tr>`).join("")}</table></div>`}
async function inventario(){let r=await db.from("inventory").select("*").order("name");content.innerHTML=`<div class=row><h3>Inventario</h3><button class=btn onclick=newInv()>+ Añadir material</button></div><div class=card><table class=table><tr><th>Ref.</th><th>Material</th><th>Cantidad</th><th>Ubicación</th><th>Estado</th><th>Acciones</th></tr>${(r.data||[]).map(x=>`<tr><td>${esc(x.reference)}</td><td>${esc(x.name)}</td><td>${x.quantity}</td><td>${esc(x.location)}</td><td><span class=tag>${esc(x.status||"")}</span></td><td><button class=smallbtn onclick="editInv('${x.id}')">Editar</button> <button class="smallbtn danger" onclick="del('inventory','${x.id}','inventario')">Eliminar</button></td></tr>`).join("")}</table></div>`}
async function noticias(){let r=await db.from("news").select("*").order("created_at",{ascending:false});content.innerHTML=`<div class=row><h3>Noticias</h3>${admin?'<button class=btn onclick=newNews()>+ Publicar</button>':""}</div>${(r.data||[]).map(x=>`<div class=card style="margin:10px 0"><h3>${esc(x.title)}</h3><span class=muted>${new Date(x.created_at).toLocaleDateString("es-ES")}</span><p>${esc(x.body)}</p>${admin?`<button class="smallbtn danger" onclick="del('news','${x.id}','noticias')">Eliminar</button>`:""}</div>`).join("")}`}
async function novedades(){let r=await db.from("updates").select("*").order("created_at",{ascending:false});content.innerHTML=`<div class=row><h3>Novedades</h3><button class=btn onclick=newUpd()>+ Añadir novedad</button></div>${(r.data||[]).map(x=>`<div class=card style="margin:10px 0"><h3>${esc(x.title)}</h3><span class=muted>${new Date(x.created_at).toLocaleDateString("es-ES")}</span><p>${esc(x.body||"")}</p><button class=smallbtn onclick="editUpd('${x.id}')">Editar</button> <button class="smallbtn danger" onclick="del('updates','${x.id}','novedades')">Eliminar</button></div>`).join("")}`}
async function perfil(){content.innerHTML=`<div class=card><h3>Mi perfil</h3><p><b>Nombre:</b> ${esc(current.full_name)}</p><p><b>Teléfono:</b> ${esc(current.phone||"No indicado")}</p><button class=btn onclick=editProfile()>Editar</button></div>`}
async function adminPage(){await load();content.innerHTML=`<div class=grid><div class="card stat"><span class=muted>Empleados</span><b>${employees.length}</b></div><div class="card stat"><span class=muted>Base de datos</span><b>OK</b></div></div><div class=section><div class=card><h3>Equipo</h3><table class=table><tr><th>Nombre</th><th>Teléfono</th><th>Rol</th></tr>${employees.map(e=>`<tr><td>${esc(e.full_name)}</td><td>${esc(e.phone||"")}</td><td>${e.role}</td></tr>`).join("")}</table></div></div>`}
function pin(){S.insertAdjacentHTML("beforeend",`<div class=modal id=modal><div class=card><button class=close onclick=modal.remove()>×</button><h3>Administración</h3><p class=muted>PIN de demostración: 1234</p><input id=p class=pin type=password maxlength=6><br><br><button class=btn onclick="if(p.value==='1234'){admin=true;modal.remove();render('admin')}else alert('PIN incorrecto')">Entrar</button></div></div>`)}
async function newNews(){let title=prompt("Título");if(!title)return;let body=prompt("Contenido")||"";let r=await db.from("news").insert({title,body});if(r.error)return alert(r.error.message);render("noticias")}
async function newUpd(){let title=prompt("Título de la novedad");if(!title)return;let body=prompt("Contenido")||"";let r=await db.from("updates").insert({title,body});if(r.error)return alert(r.error.message);render("novedades")}
async function editUpd(id){let r=await db.from("updates").select("*").eq("id",id).single();if(r.error)return alert(r.error.message);let title=prompt("Título",r.data.title);if(!title)return;let body=prompt("Contenido",r.data.body||"")||"";let u=await db.from("updates").update({title,body}).eq("id",id);if(u.error)return alert(u.error.message);render("novedades")}
async function newInv(){let name=prompt("Material");if(!name)return;let reference=prompt("Referencia")||"";let quantity=Number(prompt("Cantidad","1")||0);let location=prompt("Ubicación")||"";let status=prompt("Estado","Disponible")||"Disponible";let r=await db.from("inventory").insert({name,reference,quantity,location,status});if(r.error)return alert(r.error.message);render("inventario")}
async function editInv(id){let r=await db.from("inventory").select("*").eq("id",id).single();if(r.error)return alert(r.error.message);let name=prompt("Material",r.data.name);if(!name)return;let reference=prompt("Referencia",r.data.reference||"")||"";let quantity=Number(prompt("Cantidad",String(r.data.quantity??0))||0);let location=prompt("Ubicación",r.data.location||"")||"";let status=prompt("Estado",r.data.status||"Disponible")||"Disponible";let u=await db.from("inventory").update({name,reference,quantity,location,status}).eq("id",id);if(u.error)return alert(u.error.message);render("inventario")}
async function newShift(){let date=prompt("Fecha YYYY-MM-DD");if(!date)return;let employee_id=prompt("UUID del empleado");if(!employee_id)return;let r=await db.from("shifts").insert({date,employee_id,start_time:prompt("Inicio","08:00"),end_time:prompt("Fin","16:00"),service:prompt("Servicio","Hangar")});if(r.error)return alert(r.error.message);render("cuadrantes")}
async function del(t,id,p){if(!confirm("¿Eliminar?"))return;let r=await db.from(t).delete().eq("id",id);if(r.error)return alert(r.error.message);render(p)}
async function editProfile(){let full_name=prompt("Nombre",current.full_name);if(!full_name)return;let phone=prompt("Teléfono",current.phone||"")||"";let r=await db.from("profiles").update({full_name,phone}).eq("id",current.id);if(r.error)return alert(r.error.message);await load();current=employees.find(e=>e.id===current.id);render("perfil")}
choose();
