(function(){
  const getEmployees=()=>Array.isArray(employees)?employees:[];
  async function loadRows(){const r=await db.from('comisiones_servicio').select('id,ejercicio,fecha,lugar,created_at,updated_at').order('fecha',{ascending:false}).order('ejercicio');if(r.error)throw r.error;const rows=r.data||[];if(!rows.length)return rows;const ar=await db.from('comisiones_personal').select('comision_id,empleado_id').in('comision_id',rows.map(x=>x.id));if(ar.error&&ar.code!=='PGRST205')throw ar.error;const byId=new Map(getEmployees().map(e=>[String(e.id),e]));rows.forEach(x=>x.personal=(ar.data||[]).filter(a=>String(a.comision_id)===String(x.id)).map(a=>byId.get(String(a.empleado_id))).filter(Boolean));return rows;}
  async function renderComisionesPage(){const c=document.getElementById('content');if(!c)return;try{const rows=await loadRows();window.__comisionesCache=rows;c.innerHTML=`<div class="calendar-toolbar"><div><span class="eyebrow">ACTIVIDAD OPERATIVA</span><h3>Ejercicios / Comisiones</h3><p class="muted">Ejercicio, fecha, lugar y personal asignado.</p></div>${admin?'<button class="btn primary" onclick="comisionForm()">+ Añadir registro</button>':''}</div><div class="panel commission-panel"><div class="table-scroll"><table class="commission-table"><thead><tr><th>Ejercicio / Misión</th><th>Fecha</th><th>Lugar</th><th>Personal asignado</th>${admin?'<th>Acciones</th>':''}</tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td><strong>${esc(x.ejercicio)}</strong></td><td>${new Date(x.fecha+'T00:00:00').toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit',year:'numeric'})}</td><td>${esc(x.lugar)}</td><td>${x.personal?.length?x.personal.map(p=>`<span class="person-chip">${esc(p.nombre||p.full_name)}</span>`).join(' '):'<span class="muted">Sin personal asignado</span>'}</td>${admin?`<td><button class="table-action" onclick="comisionForm('${x.id}')">✎ Editar</button><button class="table-action danger" onclick="deleteComision('${x.id}')">🗑 Eliminar</button></td>`:''}</tr>`).join(''):`<tr><td colspan="${admin?5:4}"><div class="empty-state compact"><h3>No hay registros todavía</h3><p>Añade ejercicios, comisiones o misiones para empezar.</p></div></td></tr>`}</tbody></table></div></div>`;}catch(e){c.innerHTML=`<div class="panel error-state"><h3>No se pudieron cargar las comisiones</h3><p>${esc(e.message||e)}</p></div>`;}}
  function ensureNav(activePage=''){const nav=document.querySelector('.side-nav');if(!nav)return;let link=Array.from(nav.querySelectorAll('.side-link')).find(x=>x.dataset.comisiones==='1');if(!link){link=document.createElement('button');link.className='side-link';link.dataset.comisiones='1';link.innerHTML='<span class="side-icon">✈</span><span>Ejercicios / Comisiones</span>';link.onclick=()=>window.render('comisiones');nav.appendChild(link);}link.classList.toggle('active',activePage==='comisiones');}
  window.ensureComisionesNav=ensureNav;
  window.comisionesPage=renderComisionesPage;
  window.comisionForm=async function(id=''){if(!admin)return;try{if(!getEmployees().length&&typeof loadEmployees==='function')await loadEmployees();}catch(e){toast(e.message||'No se pudo cargar el personal','error');return;}const ex=(window.__comisionesCache||[]).find(x=>String(x.id)===String(id))||{ejercicio:'',fecha:'',lugar:'',personal:[]};const selected=new Set((ex.personal||[]).map(p=>String(p.id)));const em=[...getEmployees()].sort((a,b)=>String(a.nombre||a.full_name).localeCompare(String(b.nombre||b.full_name),'es'));openModal(`<div class="modal-head"><div><span class="eyebrow">ACTIVIDAD OPERATIVA</span><h3>${id?'Editar registro':'Nuevo registro'}</h3></div><button class="icon-btn" onclick="closeModal()">×</button></div><label>Ejercicio / misión<input id="comEjercicio" class="field" value="${esc(ex.ejercicio)}"></label><label>Fecha<input id="comFecha" class="field" type="date" value="${esc(ex.fecha||'')}"></label><label>Lugar<input id="comLugar" class="field" value="${esc(ex.lugar)}"></label><div class="assign-box"><div class="assign-title">PERSONAL ASIGNADO</div><div class="employee-select-list">${em.length?em.map(e=>`<label class="employee-option"><input type="checkbox" class="com-person" value="${esc(e.id)}" ${selected.has(String(e.id))?'checked':''}><span>${esc(e.nombre||e.full_name)}</span></label>`).join(''):`<div class="empty-state compact"><p>No hay empleados cargados. Cierra este formulario y vuelve a entrar al portal.</p></div>`}</div><p class="muted">Marca uno o varios empleados.</p></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveComision('${id}')">Guardar</button></div>`);}catch(e){toast(e.message||'No se pudo abrir el formulario','error');}};
  window.saveComision=async function(id){if(!admin)return;const ejercicio=document.getElementById('comEjercicio')?.value.trim(),fecha=document.getElementById('comFecha')?.value,lugar=document.getElementById('comLugar')?.value.trim(),empleadosSeleccionados=[...document.querySelectorAll('.com-person:checked')].map(x=>x.value);if(!ejercicio||!fecha||!lugar){toast('Completa ejercicio, fecha y lugar','warn');return;}try{let cid=id;if(id){const r=await db.from('comisiones_servicio').update({ejercicio,fecha,lugar,updated_at:new Date().toISOString()}).eq('id',id).select('id').single();if(r.error)throw r.error;cid=r.data.id;const d=await db.from('comisiones_personal').delete().eq('comision_id',cid);if(d.error)throw d.error;}else{const r=await db.from('comisiones_servicio').insert({ejercicio,fecha,lugar}).select('id').single();if(r.error)throw r.error;cid=r.data.id;}if(empleadosSeleccionados.length){const r=await db.from('comisiones_personal').insert(empleadosSeleccionados.map(empleado_id=>({comision_id:cid,empleado_id})));if(r.error)throw r.error;}closeModal();await window.render('comisiones');toast(id?'Registro actualizado':'Registro añadido');}catch(e){toast(e.message||'No se pudo guardar','error');}};
  window.deleteComision=async function(id){if(!admin)return;const x=(window.__comisionesCache||[]).find(r=>String(r.id)===String(id));if(!x||!confirm(`¿Eliminar "${x.ejercicio}"?`))return;const r=await db.from('comisiones_servicio').delete().eq('id',id);if(r.error){toast(r.error.message,'error');return;}await window.render('comisiones');toast('Registro eliminado');};

  // Integración con el render principal: mantiene el menú visible en todas las pantallas
  // y abre directamente la pantalla de Ejercicios / Comisiones.
  const baseRender=window.render;
  window.render=async function(page='inicio'){
    await baseRender(page);
    ensureNav(page);
    if(page==='comisiones') await renderComisionesPage();
  };
})();
